---
title: "README"
author: "Camila Ospina Patino"
date: "7/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Getting and Cleaning Data Project


Data Zip File Location: [UC Irvine Repo](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip "Clicking will download the data")

## Goal of the Project
1. A tidy data set 
2. A link to a Github repository with your script for performing the analysis 
3. A code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.
4. Analysis R Script

## Review Criteria

Goal | Item | Link to Item
--- | --- | ---
Analysis R Script |  run_analysis.R |  [R Script Link](https://github.com/CamilaOspinaPatino/datasciencecoursera/blob/master/run_analysis.R "run_analysis.R")
Tidy Data Set |  Clean Data Set |  [Data Set Link](https://github.com/CamilaOspinaPatino/datasciencecoursera/blob/master/tidyData.txt "tidyData.txt")
Github Repo | Repo |  [Repo Link](https://github.com/CamilaOspinaPatino/datasciencecoursera "Click to go to Repo")
CodeBook | CodeBook.md |  [Repo Link](https://github.com/CamilaOspinaPatino/datasciencecoursera/blob/master/CodeBook.md "CodeBook.md")
README | ReadingItNow |  [Repo Link](https://github.com/CamilaOspinaPatino/datasciencecoursera/blob/master/README.md "README.md")

## Contributors

FirstName | LastName | Email
--- | --- | ---
Camila |  Ospina |  <cospinap@unal.edu.co>



